backend:
  name: github
  repo: ajay17141994/hugonetlify  # Path to your GitHub repository

media_folder: "images/uploads"

collections:
  - label: "City Product Listing"
    name: "city_product"
    folder: "content/city"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "post type"
        name: "postType"
        widget: "hidden"
        default: "city"
      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
      - label: "Meta Keyword"
        name: "meta_keywords"
        widget: "string"
      - label: "Meta Author"
        name: "meta_author"
        widget: "string"
      - label: "Post for city/Sub Locality"
        name: "locality_type"
        widget: "select"
        options: ["City", "Sub-Locality"]
      - label: "Category"
        name: "categories"
        widget: "hidden"
        default: "Product Listing"
      - label: "City/Sub Locality Name"
        name: "title"
        widget: "string"
      - label: "Home page Heading"
        name: "home_pageHeading"
        widget: "string"
      - label: "Page Heading(part 1 eg.Gold Loan in City_Name)"
        name: "heading_one"
        widget: "string"
      - label: "Page Heading(Part 2)"
        name: "heading_two"
        widget: "string"
        default: "with"
      - label: "Page Heading(part 3 eg. company_name)"
        name: "heading_three"
        widget: "string"
        default: "Rupeek"
      - label: "Brief Description"
        name: "description"
        widget: "string"
      - label: "City Description related to GOLD LOAN"
        name: "body"
        widget: "markdown"
      - label: "Sub locality name where service is available separated by comma (eg. HSR LAYOUT, JP NAGAR, JAYANAGARA )"
        name: "sub_locality"
        widget: "string"
      - label: "Gold loan based city Bottom paragraph"
        name: "sub_footerData"
        widget: "string"
  - label: "Sub Locality product listing"
    name: "sub_localityProduct"
    folder: "content/subLocality"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "post type"
        name: "postType"
        widget: "hidden"
        default: "sublocality"
      - label: "Meta Description"
        name: "meta_description"
        widget: "string"
      - label: "Meta Keyword"
        name: "meta_keywords"
        widget: "string"
      - label: "Meta Author"
        name: "meta_author"
        widget: "string"
      - label: "Post for city/Sub Locality"
        name: "locality_type"
        widget: "select"
        options: ["City", "Sub-Locality"]
      - label: "Category"
        name: "categories"
        widget: "hidden"
        default: "Product Listing"
      - label: "City/Sub Locality Name"
        name: "title"
        widget: "string"
      - label: "Home page Heading"
        name: "home_pageHeading"
        widget: "string"
      - label: "Page Heading(part 1 eg.Gold Loan in City_Name)"
        name: "heading_one"
        widget: "string"
      - label: "Page Heading(Part 2)"
        name: "heading_two"
        widget: "string"
        default: "with"
      - label: "Page Heading(part 3 eg. company_name)"
        name: "heading_three"
        widget: "string"
        default: "Rupeek"
      - label: "Brief Description"
        name: "description"
        widget: "string"
      - label: "City Description related to GOLD LOAN"
        name: "body"
        widget: "markdown"
      - label: "Sub locality name where service is available separated by comma (eg. HSR LAYOUT, JP NAGAR, JAYANAGARA )"
        name: "sub_locality"
        widget: "string"
      - label: "Gold loan based city Bottom paragraph"
        name: "sub_footerData"
        widget: "string"
      